PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ex: <http://www.example.org/resources#>
PREFIX text: <http://jena.apache.org/text#>
PREFIX sdo: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?SearchTerm ?MatchURI (SAMPLE(?MatchPropertyAll) AS ?MatchProperty) ?MatchTerm ?Container ?ContainerLabel ?MethodSubType ?Status (GROUP_CONCAT(DISTINCT(?VocabCategory);separator=", ") AS ?Categories)
{
  VALUES ?EscapedSearchTerm {
    {%- for term in terms -%}
      {% if proximity %}"\"{{ term }}\"~10"{% else %}"{{ term }}" "\"{{ term }}\""{% endif %}
    {%- endfor %}
  }

  {%- if not predicate %}
    {% set predicate = "skos:definition skos:prefLabel dcterms:description skos:altLabel dcterms:identifier rdfs:label" %}
  {%- else %}
    {% set predicate = predicate %}
  {%- endif %}
  (?MatchURI ?Weight ?MatchTerm ?graph ?MatchProp) text:query ({{ predicate }} ?EscapedSearchTerm 5 ) .
    GRAPH ?g {?MatchURI ?p ?o}
    {%- if theme_uris %}
      VALUES ?theme_uri {
    {%- for theme_uri in theme_uris -%}<{{theme_uri}}>{%- endfor %}
      }
        GRAPH <https://themes> {?g dcat:theme ?theme_uri .
            ?theme_uri rdfs:label ?VocabCategory }
    {%- else %}
      OPTIONAL {
        GRAPH <https://themes> {?g dcat:theme ?theme_uri .
            ?theme_uri rdfs:label ?VocabCategory }
      }
    {%- endif %}
  OPTIONAL {
    ?MatchURI skos:prefLabel|rdfs:label|dcterms:title|sdo:name ?match_label .
    ?MatchProp skos:prefLabel|rdfs:label|dcterms:title|sdo:name ?prop_label .
    FILTER(LANGMATCHES(LANG(?prop_label), "en") || LANG(?prop_label) = "")
  }
  OPTIONAL {
    ?OptContainer skos:member ?MatchURI ;
                  skos:prefLabel ?OptContainerPrefLabel ;
                  dcterms:title ?OptContainerTitle .
  }
  OPTIONAL {
    ?MatchURI skos:inScheme ?OptContainer .
    ?OptContainer skos:prefLabel ?OptContainerLabel .
  }
  OPTIONAL {
    ?MatchURI owl:deprecated ?isDeprecated .
  }
  BIND( if (
    COALESCE(?isDeprecated, "false") = "false", "Active", "Deprecated"
    ) AS ?Status
  )
  BIND(COALESCE(?OptContainer,"") AS ?Container)
  BIND(COALESCE(?OptContainerPrefLabel,?OptContainerTitle,"") AS ?ContainerLabel)
  BIND(REPLACE(?EscapedSearchTerm, "\\\\", "") AS ?SearchTermRaw)
  BIND(REPLACE(?SearchTermRaw, "\"", "") AS ?CompletelyUnescaped)
    BIND(
      {% if proximity %}
        "Proximity Match"
      {% else %}
      IF(
        LCASE(?SearchTermRaw) = LCASE(?MatchTerm),
        "Exact Match",
        IF(
          LCASE(?CompletelyUnescaped) = LCASE(?MatchTerm) && LCASE(?SearchTermRaw) != LCASE(?MatchTerm),
          "Exact Match",
          "Wildcard Match"
          )
        )
      {% endif %}
      AS ?MethodSubType
      )
  BIND(COALESCE(?prop_label, ?MatchProp) AS ?MatchPropertyAll)
  BIND(COALESCE(?CompletelyUnescaped, ?SearchTermRaw) AS ?SearchTerm)
} GROUP BY ?g ?MatchURI ?MatchTerm ?SearchTerm ?Container ?ContainerLabel ?MethodSubType ?Status
ORDER BY DESC(?MethodSubType) DESC(?Weight)
