PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ex: <http://www.example.org/resources#>
PREFIX text: <http://jena.apache.org/text#>
PREFIX sdo: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?MatchURI (COALESCE(?prop_label, ?MatchProp) AS ?MatchProperty) ?MatchTerm ?SearchTerm ?Container ?ContainerLabel ?Weight ?ExactMatch
{
  VALUES ?EscapedSearchTerm {
    {%- for term in terms -%}
      "{{ term }}"
    {%- endfor %}
  }

  {%- if not predicate %}
    {% set predicate = "skos:definition skos:prefLabel dcterms:description skos:altLabel dcterms:identifier" %}
  {%- else %}
    {% set predicate = predicate %}
  {%- endif %}
  (?MatchURI ?RawWeight ?MatchTerm ?graph ?MatchProp) text:query ({{ predicate }} ?EscapedSearchTerm 10 ) .

  OPTIONAL {
    ?MatchURI skos:prefLabel|rdfs:label|dcterms:title|sdo:name ?match_label .
  }
  OPTIONAL {
    ?MatchProp skos:prefLabel|rdfs:label|dcterms:title|sdo:name ?prop_label .
  }
  OPTIONAL {
    ?OptContainer skos:member ?MatchURI ;
                  skos:prefLabel ?OptContainerPrefLabel .
  }
  OPTIONAL {
    ?OptContainer skos:member ?MatchURI ;
                  dcterms:title ?OptContainerTitle .
  }
  OPTIONAL {
    ?MatchURI skos:inScheme ?OptContainer .
    ?OptContainer skos:prefLabel ?OptContainerLabel .
  }
  BIND(COALESCE(?OptContainer,"") AS ?Container)
  BIND(COALESCE(?OptContainerPrefLabel,?OptContainerTitle,"") AS ?ContainerLabel)
  BIND(REPLACE(?EscapedSearchTerm, "\\\\", "") AS ?SearchTerm)
  BIND(IF(LCASE(?SearchTerm) = LCASE(?MatchTerm),"Exact Match","Wildcard Match") AS ?ExactMatch)
  BIND(ROUND(?RawWeight*100)/100 AS ?Weight)
} ORDER BY DESC(?ExactMatch) DESC(?Weight)