PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ex: <http://www.example.org/resources#>
PREFIX text: <http://jena.apache.org/text#>
PREFIX sdo: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?SearchTerm ?MatchURI ?MatchProperty ?MatchTerm ?Container ?ContainerLabel ?MethodSubType ?Status (GROUP_CONCAT(DISTINCT(?VocabCategory);separator=", ") AS ?Categories)
{
    {
      SELECT REDUCED ?MatchURI {
        VALUES ?MatchURI { {%- for term in terms -%}
        <{{term}}>
        {%- endfor %} }
        ?MatchURI ?p ?o
      }
    }
    GRAPH ?g {?MatchURI ?p ?o}
    {%- if theme_uris %}
      VALUES ?theme_uri {
    {%- for theme_uri in theme_uris -%}<{{theme_uri}}>{%- endfor %}
      }
        GRAPH <https://themes> {?g dcat:theme ?theme_uri .
            ?theme_uri rdfs:label ?VocabCategory }
    {%- else %}
      OPTIONAL {
        GRAPH <https://themes> {?g dcat:theme ?theme_uri .
            ?theme_uri rdfs:label ?VocabCategory }
      }
    {%- endif %}
    OPTIONAL {
      ?MatchURI skos:prefLabel|rdfs:label|dcterms:title|sdo:name ?MatchLabel .
    }
    OPTIONAL {
    ?OptContainer skos:member ?MatchURI ;
                 skos:prefLabel ?OptContainerLabel .
    }
    OPTIONAL {
      ?MatchURI owl:deprecated ?isDeprecated .
    }
    BIND( if (
      COALESCE(?isDeprecated, "false") = "false", "Accepted", "Deprecated"
      ) AS ?Status
    )
    BIND(?MatchURI AS ?SearchTerm)
    BIND("N/A" AS ?MatchProperty)
    BIND(COALESCE(?MatchLabel,"") AS ?MatchTerm)
    BIND("URI Match" AS ?MethodSubType)
    BIND(COALESCE(?OptContainer,"") AS ?Container)
    BIND(COALESCE(?OptContainerLabel,"") AS ?ContainerLabel)
} GROUP BY ?g ?MatchURI ?MatchProperty ?MatchTerm ?SearchTerm ?Container ?ContainerLabel ?MethodSubType ?Status
