PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ex: <http://www.example.org/resources#>
PREFIX text: <http://jena.apache.org/text#>
PREFIX sdo: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT
  ?MatchURI ?MatchProperty ?MatchTerm ?SearchTerm ?Container ?ContainerLabel ?Weight ?ExactMatch
WHERE {
  {
    {
      SELECT ?MatchURI {
        VALUES ?MatchURI { {%- for term in terms -%}
        <{{term}}>
        {%- endfor %} }
        ?MatchURI ?p ?o
      } LIMIT 1
    }
    OPTIONAL {
      ?MatchURI skos:prefLabel|rdfs:label|dcterms:title|sdo:name ?uri_label .
    }
    OPTIONAL {
    ?OptContainer skos:member ?MatchURI ;
                 skos:prefLabel ?OptContainerLabel .
    }
    BIND("" AS ?SearchTerm)
    BIND("" AS ?MatchProperty)
    BIND("" AS ?MatchTerm)
    BIND("" AS ?Weight)
    BIND("" AS ?ExactMatch)
    BIND(COALESCE(?OptContainer,"") AS ?Container)
    BIND(COALESCE(?OptContainerLabel,"") AS ?ContainerLabel)
  }
}